services:
  postgres:
    image: postgres:17.0
    container_name: letterboxd-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: letterboxd
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chrome:
    # use image seleniarm/standalone-chromium:latest for ARM based systems
    image: selenium/standalone-chrome:latest
    container_name: letterboxd-chrome
    restart: always
    ports:
      - '4444:4444'
      - '7900:7900' # VNC port for debugging
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300

volumes:
  postgres_data:
    driver: local
